#!/usr/bin/env bash
#
# Sample restore script generated by `comfyguard restore` (dry-run).
# ComfyGuard emits this script; it does NOT run it. A human, a coding agent, or
# CI reviews and runs it. It rolls an instance back to a captured baseline.
#
# It delegates the node and pip rollback to ComfyUI-Manager (comfy node
# restore-snapshot) and compensates for that path's two gaps: it does not
# re-checkout the core commit, and it skips torch/nvidia on pip restore.
#
# Never deletes: anything not in the baseline is moved to ./quarantine, not removed.

set -euo pipefail

# --- values ComfyGuard fills in from the snapshot ---------------------------
TARGET="/opt/comfyui"                                   # ComfyUI install root
MANAGER_SNAPSHOT="./baseline-manager.json"             # byte-compatible Manager copy
CORE_COMMIT="7c0d1e2f3a4b5c6d7e8f90a1b2c3d4e5f6071829"  # baseline core.commit
QUARANTINE="./quarantine/$(date -u +%Y%m%dT%H%M%SZ)"
COMFY="comfy"                                           # comfy-cli entrypoint

echo "== ComfyGuard restore =="
echo "target: ${TARGET}"
mkdir -p "${QUARANTINE}"

# 1. Pre-restore snapshot (rollback point for the rollback).
echo "[1/6] capturing pre-restore snapshot"
comfyguard snapshot "${TARGET}" --out ./pre-restore

# 2. Restore nodes + non-torch pips via ComfyUI-Manager.
#    --pip-non-url restores PyPI pins; torch/nvidia are handled in step 4.
echo "[2/6] restoring nodes and pip via comfy node restore-snapshot"
"${COMFY}" node restore-snapshot "${MANAGER_SNAPSHOT}" --pip-non-url

# 3. Re-checkout the core commit (Manager's modern restore does not do this).
#    Quarantine, do not discard, a dirty working tree.
echo "[3/6] re-checking out core commit ${CORE_COMMIT}"
if ! git -C "${TARGET}" diff --quiet; then
  echo "  working tree is dirty; stashing to quarantine (not discarding)"
  git -C "${TARGET}" stash push -u -m "comfyguard-pre-restore" || true
fi
git -C "${TARGET}" checkout "${CORE_COMMIT}"

# 4. Reinstall the torch/nvidia pins Manager skips, from the snapshot.
echo "[4/6] reinstalling pinned torch/nvidia packages"
# ComfyGuard emits the exact lines from dependencies.pip_freeze / .hashes:
#   pip install "torch==2.6.0"
# (add --require-hashes with the recorded sha256 when available)

# 5. Re-apply launch flags and Manager security level (not in the Manager format).
echo "[5/6] re-applying launch flags and Manager config"
echo "  MANUAL/gated: set --listen 127.0.0.1 in deploy/comfyui.service"
echo "  MANUAL/gated: set security_level=strong, allow_pip_install=False in config.ini"

# 6. Restart is human-only. Then verify.
echo "[6/6] restart the service (human-only), then verify:"
echo "  comfyguard diff --against baseline.json ${TARGET}   # expect an empty diff"

echo "== restore steps prepared; review each before applying =="
